services:
  - type: web
    name: alastor-n8n
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: TELEGRAM_TOKEN
        value: your_telegram_token
      - key: OPENAI_API_KEY
        value: your_openai_key
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: alastor-n8n.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_EDITOR_BASE_URL
        value: https://alastor-n8n.onrender.com
